// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id,name,email,avatar_url,is_email_verified,created_at) VALUES ($1,$2,$3,$4,$5,$6)
`

type InsertUserParams struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	IsEmailVerified bool               `json:"is_email_verified"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.AvatarUrl,
		arg.IsEmailVerified,
		arg.CreatedAt,
	)
	return err
}
